live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x505050"
blue = "0xA4C1CF"
cyan = "0xAADABF"
green = "0xAADABF"
magenta = "0xFFAF9A"
red = "0xD07057"
white = "0xC0C0C0"
yellow = "0xFFD09A"

[colors.cursor]
cursor = "0xC0C0C0"
text = "0x181818"

[colors.normal]
black = "0x181818"
blue = "0x658FA2"
cyan = "0x6EB78E"
green = "0x6EB78E"
magenta = "0xD09857"
red = "0xE8E8E8"
white = "0xC0C0C0"
yellow = "0xFFD09A"

[colors.primary]
background = "0x181818"
foreground = "0xC0C0C0"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
dynamic_padding = false

[window.padding]
x = 2
y = 2
